AdminPortal/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'motherboard' => 'mbcpus#index', as: :motherboard
  get 'acts' => 'pages#acts', as: :acts

  resources :mbcpus
  resources :memories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

AdminPortal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

AdminPortal/app/models/mbcpu.rb
class Mbcpu < ApplicationRecord
end

AdminPortal/app/models/memory.rb
class Memory < ApplicationRecord
end

AdminPortal/app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, :format => /@/
  has_secure_password
end

AdminPortal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

AdminPortal/app/controllers/mbcpus_controller.rb
class MbcpusController < ApplicationController
  before_action :set_mbcpu, only: [:show, :edit, :update, :destroy]

  # GET /mbcpus
  # GET /mbcpus.json
  def index
    @mbcpus = Mbcpu.all
  end

  # GET /mbcpus/1
  # GET /mbcpus/1.json
  def show
  end

  # GET /mbcpus/new
  def new
    @mbcpu = Mbcpu.new
  end

  # GET /mbcpus/1/edit
  def edit
  end

  # POST /mbcpus
  # POST /mbcpus.json
  def create
    @mbcpu = Mbcpu.new(mbcpu_params)

    respond_to do |format|
      if @mbcpu.save
        format.html { redirect_to @mbcpu, notice: 'Mbcpu was successfully created.' }
        format.json { render :show, status: :created, location: @mbcpu }
      else
        format.html { render :new }
        format.json { render json: @mbcpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mbcpus/1
  # PATCH/PUT /mbcpus/1.json
  def update
    respond_to do |format|
      if @mbcpu.update(mbcpu_params)
        format.html { redirect_to @mbcpu, notice: 'Mbcpu was successfully updated.' }
        format.json { render :show, status: :ok, location: @mbcpu }
      else
        format.html { render :edit }
        format.json { render json: @mbcpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mbcpus/1
  # DELETE /mbcpus/1.json
  def destroy
    @mbcpu.destroy
    respond_to do |format|
      format.html { redirect_to mbcpus_url, notice: 'Mbcpu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mbcpu
      @mbcpu = Mbcpu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mbcpu_params
      params.require(:mbcpu).permit(:type, :brend, :model, :description)
    end
end

AdminPortal/app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]

  # GET /memories
  # GET /memories.json
  def index
    @memories = Memory.all
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
  end

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories
  # POST /memories.json
  def create
    @memory = Memory.new(memory_params)

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: 'Memory was successfully created.' }
        format.json { render :show, status: :created, location: @memory }
      else
        format.html { render :new }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memories/1
  # PATCH/PUT /memories/1.json
  def update
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to @memory, notice: 'Memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory }
      else
        format.html { render :edit }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @memory.destroy
    respond_to do |format|
      format.html { redirect_to memories_url, notice: 'Memory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_params
      params.require(:memory).permit(:type, :brend, :size, :description)
    end
end

AdminPortal/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def calendar
  end

  def timeline
  end

  def user_profile
  end

  def acts
  end
end

AdminPortal/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    # @users = User.all
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  #  render partial: '/shared/login'
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation, :email)
    end
end

AdminPortal/app/helpers/application_helper.rb
module ApplicationHelper
end

AdminPortal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminPortal</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- start: GOOGLE FONTS -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
    <!-- end: GOOGLE FONTS -->
    <!-- start: MAIN CSS -->
    <%= stylesheet_link_tag '/assets/bootstrap.min', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/font-awesome.min', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/themify-icons.min', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/animate.min', media: "screen", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/perfect-scrollbar.min', media: "screen", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/switchery.min', media: "screen", 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag '/assets/styles', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/plugins', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/theme-5', media: "all", 'data-turbolinks-track': 'reload' %>
    <!-- end: MAIN CSS -->

    <%= stylesheet_link_tag '/assets/select2.min', media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/assets/DT_bootstrap', media: "all", 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div id="app">
      <%= render 'shared/sidebar' %>
      <div class="app-content">
        <%= render 'shared/navbar' %>
        <div class="main-content" >
          <div class="wrap-content container" id="container">
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

AdminPortal/app/views/mbcpus/_form.html.erb
<%= form_for(mbcpu) do |f| %>
  <% if mbcpu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mbcpu.errors.count, "error") %> prohibited this mbcpu from being saved:</h2>
      <ul>
      <% mbcpu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
    <fieldset>
      <legend>MotherBoard/CPU</legend>
          <div class="form-group">
              <%= f.select(:type, [["Select type", 0], ["MotherBoard"], ["CPU"]], {:disabled => 0, :selected => 0}, {class: 'cs-select cs-skin-elastic'}) %>
          </div>
          <div class="form-group">
              <%= f.text_field :brend, class: "form-control", placeholder: "brend" %>
          </div>
          <div class="form-group">
              <%= f.text_field :model, class: "form-control", placeholder: "model" %>
          </div>
      <div class="panel panel-white">
        <div class="panel-heading">
          <div class="panel-title">
            Descriptions
          </div>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <div class="note-editor">
              <%= f.text_area :description, class: "form-control autosize area-animated-control"%>
            </div>
          </div>
        </div>
      </div>
      <%= f.button :submit, class: "btn btn-primary pull-right" do %>
          Create item <i class="fa fa-plus"></i>
      <% end %>
    </fieldset>
    </div>
  </div>
<% end %>

AdminPortal/app/views/mbcpus/edit.html.erb
<h1>Editing Mbcpu</h1>

<%= render 'form', mbcpu: @mbcpu %>

<%= link_to 'Show', @mbcpu %> |
<%= link_to 'Back', mbcpus_path %>

AdminPortal/app/views/mbcpus/index.html.erb
<p id="notice"><%= notice %></p>
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">Equipments Tables</h1>
      <span class="mainDescription">Refers to data arranged in rows and columns. A spreadsheet, for example, is a table. In relational database management systems, all information is stored in the form of tables. <small class="block">Webopedia - Online Tech Dictionary for IT Professionals</small></span>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>Tables</span>
      </li>
      <li class="active">
        <span>Equipments</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw bg-white">
  <div class="row">
    <div class="col-md-1 space20">
      <div class="btn-group">
        <a href="#" data-toggle="dropdown" class="btn btn-wide btn-success dropdown-toggle">
          Add new <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li role="presentation" class="dropdown-header">
            Select equipment
          </li>
          <li>
            <%= link_to 'PC', new_mbcpu_path %>
          </li>
          <li>
            <%= link_to 'Monitor', new_mbcpu_path %>
          </li>
          <li>
            <%= link_to 'UPS ', new_mbcpu_path %>
          </li>
          <li class="divider"></li>
          <li role="presentation" class="dropdown-header">
            Additional equipment
          </li>
          <li>
            <%= link_to 'Mouse etc.', new_mbcpu_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h5 class="over-title margin-bottom-15">Computers <span class="text-bold"> Table</span></h5>
      <p>
        DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon the foundations of progressive enhancement, and will add advanced interaction controls to any HTML table.
      </p>
      <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
        <thead>
        <tr>
          <th>Inv No.</th>
          <th class="hidden-xs">Motherboard</th>
          <th>Memory (MB)</th>
          <th class="hidden-xs">CPU</th>
          <th>SSD (GB)</th>
          <th class="hidden-xs">HDD (GB)</th>
          <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>0915</td>
          <td class="hidden-xs">Gigabyte Technology Co.,
            Ltd. Z97M-D3H
          </td>
          <td>16 384</td>
          <td class="hidden-xs">Intel Core i5-4570</td>
          <td>120</td>
          <td class="hidden-xs">1 000</td>
          <td><span class="label label-sm label-success">Active</span></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- end: DYNAMIC TABLE -->
<!-- start: CONDENSED TABLE -->
<div class="container-fluid container-fullw bg-white">
  <div class="row">
    <div class="col-md-6">
      <h5 class="over-title margin-bottom-15">Monitors <span class="text-bold"> Table</span></h5>
      <table class="table table-striped table-bordered table-hover table-full-width" id="sample_3">
        <thead>
        <tr>
          <th>Inv No.</th>
          <th class="hidden-xs">Brend</th>
          <th>Model</th>
          <th class="hidden-xs">Status</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>M017</td>
          <td class="hidden-xs">BenQ</td>
          <td>BNQ78CE</td>
          <td class="hidden-xs"><span class="label label-sm label-success">Active</span></td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <h5 class="over-title margin-bottom-15">UPS <span class="text-bold"> Table</span></h5>
      <table class="table table-striped table-bordered table-hover table-full-width" id="sample_4">
        <thead>
        <tr>
          <th>Inv No.</th>
          <th class="hidden-xs">Brend</th>
          <th>Model</th>
          <th class="hidden-xs">Status</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>US-011</td>
          <td class="hidden-xs">IPPon</td>
          <td>Back Office 600</td>
          <td class="hidden-xs"><span class="label label-sm label-success">Active</span></td>
        </tr>
        </tbody>
      </table>
    </div>
    </div>
  </div>
</div>
<!-- end: CONDENSED TABLE -->
<!-- start: DYNAMIC TABLE -->

<%= render 'shared/mainjs' %>
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<%= javascript_include_tag '/assets/select2.min' %>
<%= javascript_include_tag '/assets/jquery.dataTables.min' %>
<%= javascript_include_tag '/assets/table-data' %>
<script>
  jQuery(document).ready(function() {
    Main.init();
    TableData.init();
  });
</script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->

AdminPortal/app/views/mbcpus/new.html.erb
<head>
  <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
  <%= stylesheet_link_tag '/assets/jquery.bootstrap-touchspin.min', media: "screen", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/assets/select2.min', media: "screen", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/assets/bootstrap-datepicker3.standalone.min', media: "screen", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/assets/bootstrap-timepicker.min', media: "screen", 'data-turbolinks-track': 'reload' %>
  <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
</head>

<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">New Equipments</h1>
      <span class="mainDescription">We set out to create an easy, powerful and versatile form layout system. A combination of form styles and the Bootstrap grid means you can do almost anything.</span>
    </div>
  </div>
</section>
<!-- end: PAGE TITLE -->



<div class="container-fluid container-fullw bg-white">
  <div class="row">
    <div class="col-md-8">
        <%= render 'form', mbcpu: @mbcpu %>
    </div>
  </div>
</div>

<%= link_to 'Back', mbcpus_path %>

<%= render 'shared/mainjs' %>
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<%= javascript_include_tag '/assets/jquery.maskedinput.min' %>
<%= javascript_include_tag '/assets/jquery.bootstrap-touchspin.min' %>
<%= javascript_include_tag '/assets/autosize.min' %>
<%= javascript_include_tag '/assets/classie' %>
<%= javascript_include_tag '/assets/selectFx' %>
<%= javascript_include_tag '/assets/select2.min' %>
<%= javascript_include_tag '/assets/bootstrap-datepicker.min' %>
<%= javascript_include_tag '/assets/bootstrap-timepicker.min' %>
<%= javascript_include_tag '/assets/form-elements' %>
<script>
  jQuery(document).ready(function() {
    Main.init();
    FormElements.init();
  });
</script>
<!-- end: JavaScript Event Handlers for this page -->

AdminPortal/app/views/mbcpus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @mbcpu.type %>
</p>

<p>
  <strong>Brend:</strong>
  <%= @mbcpu.brend %>
</p>

<p>
  <strong>Model:</strong>
  <%= @mbcpu.model %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mbcpu.description %>
</p>

<%= link_to 'Edit', edit_mbcpu_path(@mbcpu) %> |
<%= link_to 'Back', mbcpus_path %>

AdminPortal/app/views/memories/_form.html.erb
<%= form_for(memory) do |f| %>
  <% if memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
      <% memory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :brend %>
    <%= f.text_field :brend %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AdminPortal/app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form', memory: @memory %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

AdminPortal/app/views/memories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memories</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Brend</th>
      <th>Size</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memories.each do |memory| %>
      <tr>
        <td><%= memory.type %></td>
        <td><%= memory.brend %></td>
        <td><%= memory.size %></td>
        <td><%= memory.description %></td>
        <td><%= link_to 'Show', memory %></td>
        <td><%= link_to 'Edit', edit_memory_path(memory) %></td>
        <td><%= link_to 'Destroy', memory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memory', new_memory_path %>

AdminPortal/app/views/memories/new.html.erb
<h1>New Memory</h1>

<%= render 'form', memory: @memory %>

<%= link_to 'Back', memories_path %>

AdminPortal/app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @memory.type %>
</p>

<p>
  <strong>Brend:</strong>
  <%= @memory.brend %>
</p>

<p>
  <strong>Size:</strong>
  <%= @memory.size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @memory.description %>
</p>

<%= link_to 'Edit', edit_memory_path(@memory) %> |
<%= link_to 'Back', memories_path %>

AdminPortal/app/views/pages/acts.html.erb
<h1>Pages#acts</h1>
<p>Find me in app/views/pages/acts.html.erb</p>

AdminPortal/app/views/pages/calendar.html.erb
<h1>Pages#calendar</h1>
<p>Find me in app/views/pages/calendar.html.erb</p>

AdminPortal/app/views/pages/timeline.html.erb
<h1>Pages#timeline</h1>
<p>Find me in app/views/pages/timeline.html.erb</p>

AdminPortal/app/views/pages/user_profile.html.erb
<h1>Pages#user_profile</h1>
<p>Find me in app/views/pages/user_profile.html.erb</p>

AdminPortal/app/views/shared/_footer.html.erb
<!-- start: FOOTER -->
<footer>
  <div class="footer-inner">
    <div class="pull-left">
      &copy; <span class="current-year"></span><span class="text-bold text-uppercase"> Casper</span>. <span>All rights reserved</span>
    </div>
    <div class="pull-right">
      <span class="go-top"><i class="ti-angle-up"></i></span>
    </div>
  </div>
</footer>
<!-- end: FOOTER -->

AdminPortal/app/views/shared/_mainjs.html.erb
<!-- start: MAIN JAVASCRIPTS -->
<%= javascript_include_tag '/assets/jquery.min' %>
<%= javascript_include_tag '/assets/bootstrap.min' %>
<%= javascript_include_tag '/assets/modernizr' %>
<%= javascript_include_tag '/assets/jquery.cookie' %>
<%= javascript_include_tag '/assets/perfect-scrollbar.min' %>
<%= javascript_include_tag '/assets/switchery.min' %>
<!-- end: MAIN JAVASCRIPTS -->
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<%= javascript_include_tag '/assets/Chart.min' %>
<%= javascript_include_tag '/assets/jquery.sparkline.min' %>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<!-- start: CLIP-TWO JAVASCRIPTS -->
<%= javascript_include_tag '/assets/main' %>
<!-- start: JavaScript Event Handlers for this page -->
<%= javascript_include_tag '/assets/index' %>
<!-- end: JavaScript Event Handlers for this page -->
<!-- end: CLIP-TWO JAVASCRIPTS -->

AdminPortal/app/views/shared/_sidebar.html.erb
<!-- sidebar -->
<div class="sidebar app-aside" id="sidebar">
  <div class="sidebar-container perfect-scrollbar">
    <nav>
      <!-- start: SEARCH FORM -->
      <div class="search-form">
        <a class="s-open" href="#">
          <i class="ti-search"></i>
        </a>
        <form class="navbar-form" role="search">
          <a class="s-remove" href="#" target=".navbar-form">
            <i class="ti-close"></i>
          </a>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search...">
            <button class="btn search-button" type="submit">
              <i class="ti-search"></i>
            </button>
          </div>
        </form>
      </div>
      <!-- end: SEARCH FORM -->
      <!-- start: MAIN NAVIGATION MENU -->
      <div class="navbar-title">
        <span>Main Navigation</span>
      </div>
      <ul class="main-navigation-menu">
        <li class="active open">
          <a href="<%= root_path %>">
            <div class="item-content">
              <div class="item-media">
                <i class="ti-home"></i>
              </div>
              <div class="item-inner">
                <span class="title"> Dashboard </span>
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <div class="item-content">
              <div class="item-media">
                <i class="ti-layout-grid2"></i>
              </div>
              <div class="item-inner">
                <span class="title"> Tables </span><i class="icon-arrow"></i>
              </div>
            </div>
          </a>
          <ul class="sub-menu">
            <li>
              <a href="">
                <span class="title">Inventory Tables</span>
              </a>
            </li>
            <li>
              <a href="<%= motherboard_path %>">
                <span class="title">Equipments Tables</span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="title">Additional Tables</span>
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:void(0)">
            <div class="item-content">
              <div class="item-media">
                <i class="ti-layers-alt"></i>
              </div>
              <div class="item-inner">
                <span class="title"> Pages </span><i class="icon-arrow"></i>
              </div>
            </div>
          </a>
          <ul class="sub-menu">
            <li>
              <a href="">
                <span class="title">User Profile</span>
              </a>
            </li>
            <li>
              <a href="<%= users_path %>">
                <span class="title">Users</span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="title">Acts</span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="title">Timeline</span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="title">Calendar</span>
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="maps.html">
            <div class="item-content">
              <div class="item-media">
                <i class="ti-location-pin"></i>
              </div>
              <div class="item-inner">
                <span class="title"> Maps </span>
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="charts.html">
            <div class="item-content">
              <div class="item-media">
                <i class="ti-pie-chart"></i>
              </div>
              <div class="item-inner">
                <span class="title"> Charts </span>
              </div>
            </div>
          </a>
        </li>
      </ul>
      <!-- end: MAIN NAVIGATION MENU -->
      <!-- start: CORE FEATURES -->
      <div class="navbar-title">
        <span>Core Features</span>
      </div>
      <ul class="folders">
        <li>
          <a href="pages_calendar.html">
            <div class="item-content">
              <div class="item-media">
                <span class="fa-stack"> <i class="fa fa-square fa-stack-2x"></i> <i class="fa fa-calendar fa-stack-1x fa-inverse"></i> </span>
              </div>
              <div class="item-inner">
                <span class="title"> Calendar </span>
              </div>
            </div>
          </a>
        </li>
      </ul>
      <!-- end: CORE FEATURES -->
      <!-- start: DOCUMENTATION BUTTON -->
      <div class="wrapper">
        <a href="documentation.html" class="button-o">
          <i class="ti-help"></i>
          <span>Documentation</span>
        </a>
      </div>
      <!-- end: DOCUMENTATION BUTTON -->
    </nav>
  </div>
</div>
<!-- / sidebar -->